platform :ios, '11.0'

target 'Plugin' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Capacitor'
  
  # Pods for firebase conneciton
  pod 'Firebase/Core'
  pod 'Firebase/Analytics'
end

target 'PluginTests' do
  use_frameworks!

  pod 'Capacitor'
  
  # Pods for firebase conneciton
  pod 'Firebase/Core'
  pod 'Firebase/Analytics'
end
